name: shadat_pubg
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  audioplayers: ^6.0.0
  clipboard: ^0.1.3
  cloud_firestore: ^5.2.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  share_plus: null
  url_launcher: ^6.3.0
  whatsapp_unilink: ^2.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri.ttf
